Can read the source file?  0
Executing on  maggie45.iro.umontreal.ca
HOSTNAME: maggie45.iro.umontreal.ca
PATH: /usr/lib64/openmpi/bin:/opt/condor/bin:/opt/lisa/os/epd-7.1.2/bin:/opt/lisa/os/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/diro/bin
PYTHONPATH: /usr/lib64/python2.7/site-packages/openmpi:/opt/lisa/byhost/lib/python2.7/site-packages::/opt/lisa/os/lib/python2.7/site-packages:/opt/lisa/os/lib/python2.7/site-packages/vtk_python::/data/lisatmp/ift6266h14/belius/lib/python2.7/site-packages:/data/lisatmp/ift6266h14/belius/lib/python2.7/site-packages
LD_LIBRARY_PATH: /usr/lib64/openmpi/lib:/opt/lisa/byhost/lib:/opt/lisa/os/lib/vtk:/opt/lisa/os/lib/intelmkl/lib/32:/opt/lisa/os/lib:/opt/lisa/os/lib64:/usr/local/lib:/usr/lib64/atlas/:/opt/lisa/os/python2.4/lib/::/opt/lisa/os/lib32:/opt/lisa/byhost/lib32
OMP_NUM_THREADS: 1
CONDOR_JOB_LOGDIR: LOGS.NOBACKUP/model_spec___1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-18-19-20-21-22-23-24-25-26-27-28-29-30__.yaml_2014-02-18_01-07-29.417273
HOME: /u/belius
GlobalJobId = "zappa8.iro.umontreal.ca#1290.8#1392703658"
/data/lisatmp/ift6266h14/belius/synthesis_1_MLP/learn_own_data_samples_serious/oo
nb args: 1
Running: command: "/data/lisatmp/ift6266h14/belius/pylearn2/pylearn2/scripts/train.py /data/lisatmp/ift6266h14/belius/synthesis_1_MLP/learn_own_data_samples_serious/oo/model_spec_9.yaml"
Can execute the cmd?  1
/data/lisatmp/ift6266h14/belius/lib/python2.7/site-packages/pylearn2-0.1dev-py2.7.egg/pylearn2/models/mlp.py:39: UserWarning: MLP changing the recursion limit.
  warnings.warn("MLP changing the recursion limit.")
Traceback (most recent call last):
  File "/data/lisatmp/ift6266h14/belius/pylearn2/pylearn2/scripts/train.py", line 99, in <module>
    train_obj = serial.load_train_file(args.config)
  File "/data/lisatmp/ift6266h14/belius/lib/python2.7/site-packages/pylearn2-0.1dev-py2.7.egg/pylearn2/utils/serial.py", line 492, in load_train_file
    return yaml_parse.load_path(config_file_path, environ=environ)
  File "/data/lisatmp/ift6266h14/belius/lib/python2.7/site-packages/pylearn2-0.1dev-py2.7.egg/pylearn2/config/yaml_parse.py", line 97, in load_path
    return load(content, environ=environ, **kwargs)
  File "/data/lisatmp/ift6266h14/belius/lib/python2.7/site-packages/pylearn2-0.1dev-py2.7.egg/pylearn2/config/yaml_parse.py", line 59, in load
    return instantiate_all(proxy_graph)
  File "/data/lisatmp/ift6266h14/belius/lib/python2.7/site-packages/pylearn2-0.1dev-py2.7.egg/pylearn2/config/yaml_parse.py", line 151, in instantiate_all
    graph[key] = instantiate_all(graph[key])
  File "/data/lisatmp/ift6266h14/belius/lib/python2.7/site-packages/pylearn2-0.1dev-py2.7.egg/pylearn2/config/yaml_parse.py", line 151, in instantiate_all
    graph[key] = instantiate_all(graph[key])
  File "/data/lisatmp/ift6266h14/belius/lib/python2.7/site-packages/pylearn2-0.1dev-py2.7.egg/pylearn2/config/yaml_parse.py", line 151, in instantiate_all
    graph[key] = instantiate_all(graph[key])
  File "/data/lisatmp/ift6266h14/belius/lib/python2.7/site-packages/pylearn2-0.1dev-py2.7.egg/pylearn2/config/yaml_parse.py", line 160, in instantiate_all
    graph = graph.instantiate()
  File "/data/lisatmp/ift6266h14/belius/lib/python2.7/site-packages/pylearn2-0.1dev-py2.7.egg/pylearn2/config/yaml_parse.py", line 224, in instantiate
    self.instance = checked_call(self.cls, self.kwds)
  File "/data/lisatmp/ift6266h14/belius/lib/python2.7/site-packages/pylearn2-0.1dev-py2.7.egg/pylearn2/utils/call_check.py", line 98, in checked_call
    return to_call(**kwargs)
  File "/data/lisatmp/ift6266h14/belius/synthesis_1_MLP/learn_own_data_samples_serious/oo/my_data.py", line 28, in __init__
    self.Xraw = numpy.zeros( (num_examples,xsamples) )
MemoryError
